version: "3"
services:
  application:
    build: app
    ports:
      - "8080:8080"
      - "8010:8010"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    depends_on:
      - prometheus
  spring-boot-admin:
    build: spring-boot-admin
    ports:
      - "7070:7070"
    deploy:
      resources:
        limits:
          memory: 256M
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus