server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: app
  boot:
    admin:
      client:
        url: http://spring-boot-admin:7070
  jmx:
    enabled: true